[build-system]
requires = ["scikit-build-core>=0.5.0", "pybind11>=2.11.0"]
build-backend = "scikit_build_core.build"

[project]
name = "math-basic"
version = "0.1.4"
description = "Bare-metal SIMD-accelerated math library for Python"
requires-python = ">=3.9"

[tool.scikit-build]
cmake.version = ">=3.18"
build-dir = "build/{wheel_tag}"
wheel.packages = ["src/math_basic"]